import asyncio
import os
import sys

# Mock imports if running outside container
try:
    from skills.office_suite.handler import OfficeSkill
    from skills.office_suite.schema import GenerateDocument, DocumentElement
except ImportError:
    print("Error: Dependencies missing. Please run: pip install -r requirements.txt")
    sys.exit(1)

async def test_office():
    print("--- Testing Office Suite Skill ---")
    skill = OfficeSkill()
    
    # Test 1: DOCX
    print("\n[1] Generating Word Document...")
    docx_params = {
        "file_name": "test_report",
        "doc_type": "docx",
        "title": "SGR Core Test Report",
        "elements": [
            {"type": "heading", "content": "Introduction"},
            {"type": "paragraph", "content": "This is a test report generated by SGR Core Office Skill."},
            {"type": "bullet_list", "content": "Feature 1: Docx generation"},
            {"type": "bullet_list", "content": "Feature 2: Pptx generation"}
        ]
    }
    res = await skill.execute(docx_params)
    print(f"Result: {res}")
    
    # Test 2: PPTX
    print("\n[2] Generating PowerPoint...")
    pptx_params = {
        "file_name": "test_presentation",
        "doc_type": "pptx",
        "title": "SGR Features",
        "elements": [
            {"type": "heading", "content": "Slide 1: Overview"},
            {"type": "bullet_list", "content": "Automated slides"},
            {"type": "bullet_list", "content": "Clean layout"}
        ]
    }
    res = await skill.execute(pptx_params)
    print(f"Result: {res}")
    
    # Check files
    if os.path.exists("generated_files/test_report.docx"):
        print("\nSUCCESS: test_report.docx created.")
    else:
        print("\nFAIL: test_report.docx missing.")

if __name__ == "__main__":
    asyncio.run(test_office())
